language: r
sudo: required
cache: packages
r_packages:
- remotes
- covr
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("kwb-r/kwb.pkgbuild")'
    deploy:
      provider: script
      script: Rscript -e 'kwb.pkgbuild::deploy_site_github_with_extra_files(vignettes_file_pattern_to_copy = "\\.pdf$")'
      skip_cleanup: 'true'
  - r: oldrel
