#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("dr.db_download(fromInternet = FALSE) works", {

  kwb.qmra:::dr.db_download(fromInternet = FALSE)
})


test_that("dr.db_download(fromInternet = TRUE) works", {
  
  kwb.qmra:::dr.db_download(fromInternet = TRUE)
})
