#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("report_workflow() works", {

  kwb.qmra:::report_workflow(report_output_dir = tempdir(), openReport = FALSE)
  testthat::skip_on_appveyor()
   kwb.qmra:::report_workflow()
})

