#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:57.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("default_max() works", {

  f <- kwb.qmra:::default_max

  expect_error(
    kwb.qmra:::default_max()
    # Argument "org_max" fehlt (ohne Standardwert)
  )

})
