#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:58.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("id_columns_to_integer() works", {

  f <- kwb.qmra:::id_columns_to_integer

  expect_error(
    f()
    # Argument "data" fehlt (ohne Standardwert)
  )

})
