#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:57.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("print_repeatings_exposures() works", {

  f <- kwb.qmra:::print_repeatings_exposures

  expect_error(
    f()
    # Argument "config" fehlt (ohne Standardwert)
  )

})
