#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:56.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("opencpu_simulate_risk() works", {

  f <- kwb.qmra:::opencpu_simulate_risk

  kwb.qmra:::opencpu_simulate_risk()

})
