#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:55.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_risk_total_stats_lean() works", {

  f <- kwb.qmra:::get_risk_total_stats_lean

  expect_error(
    f()
    # Argument "config" fehlt (ohne Standardwert)
  )

})
