#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("create_random_distribution(type = 'uniform') works", {
  
  kwb.qmra:::create_random_distribution(type = "uniform")
})


test_that("create_random_distribution(type = 'triangle') works", {
  
  kwb.qmra:::create_random_distribution(type = "triangle")
})

test_that("create_random_distribution(type = 'value') works", {
  
  kwb.qmra:::create_random_distribution(type = "value")
})

test_that("create_random_distribution(type = 'norm') works", {
  
  kwb.qmra:::create_random_distribution(type = "norm")
})

test_that("create_random_distribution(type = 'lognorm') works", {
  
  kwb.qmra:::create_random_distribution(type = "lognorm")
})

test_that("create_random_distribution(type = 'abc') throws ERROR", {
  
  expect_error(kwb.qmra:::create_random_distribution(type = "abc"))
})