#
# This test file has been generated by kwb.test::create_test_files()
# launched by user mrustl on 2021-02-23 15:12:54.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("group_by_treatment_and_pathogen_group() works", {

  f <- kwb.qmra:::group_by_treatment_and_pathogen_group

  expect_error(
    f()
    # Argument "lean" fehlt (ohne Standardwert)
  )

})
