#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("backcalcHelper_infectionRisk_perDay() works", {

  expect_error(kwb.qmra:::backcalcHelper_infectionRisk_perDay())
})

